# Generated by Django 5.2.6 on 2025-09-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
